define ({
    // 此处定义了所有form组件缺省语言包
    //全局设置
    "Delete":"删除",
    "Remark":"备注",
    "Submit":"提交",
    "Cancel":"取消",
    "OK":"确认",
    "Tips":"提示",
    "Close":"关闭",
    "Open":"打开",
    "Add":"添加",
    "Edit":"编辑",
    "Select":"选择",
    "Preview":"预览",
    //表单
    "Administrator Tools":"管理员工具",
    "Flow Log":"流转操作记录",
    //表单操作部分
    "delete":"删除",
    "submit":"提交",
    "save":"保存",
    "expand":"展开",
    "expandall":"展开全部区段",
    "collapse":"折叠",
    "collapseall":"折叠全部区段",
    "invalide":"作废",
    "invalidedesc":"取消流程/作废/终止",
    "close":"关闭",
    "closedesc":"关闭不保存",

    "Return to the  drafter":"返回起草人",
    "Return to the previous approver":"返回上一环节",
    "Reminders  approver":"提醒处理人",
    "Reminders":"提醒",
    "Are you sure close the document without saving":"您确认要不做保存就关闭文档？",
    "Please wait":"请等待……",
    "Continue":"继续",
    "The operation failed":"操作失败",
    "Are you sure":"请确认",
    "Do you want to save the document":"是否保存文档？",
    "Do you want to submit the document":"是否提交文档？",
    "Do you want to invalidate the document":"是否作废此文档？",
    "Do you want to deal with permissions to be forwarded to another approver":"是否要将权限转移给新的处理人",
    "Do you want to save the file without checking the validity of the input":"是否保存文件而不检查输入的有效性?",
    "Invalid parameter, confirm parameters must have a return value, please contact your administrator":"无效参数，confirm必须返回一个值，请与管理员联系！",
    "The current document have been  edit and save by others, please re-open the editor and submit or save":"当前文档已被其他人编辑并保存，请重新打开后再进行操作",
    //以下文字在ls内
    "Universalid":"文档标识符",
    "Agent Error":"程序错误",
    "Save Success":"保存成功",
    "Next step":"下一环节",
    "Status":"当前状态",
    "Approver":"处理人",
    "Operation was successful":"操作成功",
    "Submitted successfully, waiting for the system has finished processing":"提交成功，等待系统完成后续处理",
    "The document has been forwarded to":"文档已经转发给处理人",
    "The process has been terminated":"流程已被终止",
    "Create a new process documentation":"创建新流程文档",
    "Unknown error":"未知错误",
    "An unknown error into debug mode, collect error and sent to noteshelp.":"未知错误，请进入调试模式，收集错误并发送给技术支持人员。",
    //转发
    "Transfer":"转发",
    "Transfer To":"转发至",
    "Transfer to other":"转他人处理",
    "Please select transfer to":"请要选择转发人",

    cancel:"取消",
    ok:"确认",
    confirm:"确认",
    //提醒消息
    "Can not find the application database":"没有找到应用数据库",
    "Please contact the administrator.":"请与系统管理员联系",
    "Have taken place in the e-mail to remind $user":"已经提醒用户 $user 进行处理",
    "You have sent reminders, do not re-send":"你已经发生过催办邮件",
    //状态操作
    "Can handle state":"选择要处理的环节：",
    "The current deal with":"当前处理人：",
    "The current state of":"当前状态：",
    "Creator":"创建人：",
    "Creation time":"创建时间：",
    "Document Number":"流程单号：",

    //区段
    "Signature":"签名:",
    //附件组件语言包
    attachment:"附件",
    attachmentselect:"选择文件",
    upload:"上传",
    uploadtitle:"文件上传",
    uploadinstructions:"文件大小限制10MB，如果你的文件超过10MB，请使用压缩软件分块压缩后再进行上传",
    uploaderrortitle:"上传错误",
    uploaderror:"上传出错，这通常是由附件超过10MB引起，请检查你的附件大小。",
    filetypeerror:"该文件类型不允许上传，请重新选择文件。",
    pleaseselectfile:"请选择要上传的文件",
    uploading:"正在上传请稍候……",
    deleting:"正在删除附件……",
    delerrortitle:"删除错误",
    delereordescript:"附件删除出错，如果你是当前文档作者，请与管理员联系。",
    "The file name can not contain the following characters:":"文件名内不能包含以下字符:",
    "Invalid file or zero-byte file, please re-upload.":"无效文件或零字节文件，请重新上传。",
    "Invalid file":"异常文件",
    "Tables failed to initialize, Please Refresh try.If the problem persists, please contact management.":"表格初始化失败，请稍候刷新再试 。<br>如果问题依然存在，请联系管理。",
    "Please save the document and then download or preview.":"请先保存文档然后再下载或预览",
    "End":"End"
})