define ({
    // 此处定义了所有form组件缺省语言包
    //全局设置
    "LABEL":"XXX",
    "Home":"首页",
    "Login":"登录",
    "Logout":"注销",
    "Refresh":"刷新",
    "Todo":"Todo",
    "Notes":"通知",
    "Password":"密码",
    "Change Password":"修改密码",
    "Mail":"邮件",
    "User Name":"用户名",
    "Name":"名称",
    "User":"用户",
    "BBS":"BBS",
    "Settings":"设置",
    "Person Settings":"个人设置",
    "Internal Forum":"内部论坛",
    "IT Support":"IT 支持",
    "Welcome":"欢迎您",
    "Today":"今日",
    "Today is":"今天是",
    "Week":"周",
    "Service Hotline":"服务热线",
    "XXX Digital Technology Co., Ltd. All Rights Reserved":"版权所有：XXX数字技术股份有限公司",
    "Select department":"选择部门",
    "Root":"根",
    "Delete":"删除",
    "Remark":"备注",
    "Submit":"提交",
    "Cancel":"取消",
    "OK":"确定",
    "Tips":"提示",
    "Close":"关闭",
    "Open":"打开",
    "Add":"添加",
    "Edit":"编辑",
    "Copy":"复制",
    "Copy success.":"复制成功！",
    "The browser does not support auto-copy, manually copy the following text.":
        "浏览器不支持自动复制，请手动复制下面的文本。",
    "Select":"选择",
    "Empty":"清空",
    "Clear":"清除",
    "Search":"搜索",
    "Please Select":"请选择",
    "Invert Selection":"反选",
    "Click the path selection":"单击路径选择",
    "Select All":"全选",
    "Module failed to load":"模块加载失败",
    "This problem may be due to network or program error":"此问题可能是由于网络或程序错误造成 ",
    "Later to refresh such as invalid, please contact the administrator or developer":"稍后刷新如无效,请联系管理员或开发人员",
    "Equal":"等于",
    "Greater":"大于",
    "Less":"小于",
    "End":"End"
})