define ({
    "OK":"确定",
    "Upload":"上传",
    "Cancel":"取消",
    "Cancel All":"取消全部",
    "Select":"选择",
    "Select File":"选择文件",
    "Select Files":"选择文件",
    "Close":"关闭",
    "Type":"",
    "Name":"文件名",
    "Size":"大小",
    "Status":"当前状态",
    "Waiting":"等待上传",
    "Waiting to complete":"正在整理",
    "Upload complete":"上传完成",
    "Upload Error":"上传失败",
    "File name":"文件名",
    "File size":"文件大小",
    "Message":"信息",
    "Error Code":"错误编号",
    "Error Message":"错误信息",
    "Please Select Files":"请选择文件",
    "Select too many files":"选择文件数量太多",
    "You have attempted to queue too many files.":"你选择的文件数量超出一次允许上传数量限额.",
    "You have reached the upload limit.":"已经达到上传数量限额，不能再添加文件.",
    "You may select one file.":"你可以选择一个文件.",
    "You may select up to $1 files.":"您最多可以选择$1个文件.",

    "Select Fail":"选择失败",
    "File size exceeds":"文件大小超出",
    "Size limit":"单个文件限额",
    "0-byte file":"0字节文件",
    "Invalid File Type":"文件类型错误",
    "Allow file type":"可上传文件类型",
    "Unhandled Error":"未知错误",
    "Cancelled":"用户取消",
    "Stopped":"用户终止",


    "Upload Error":"上传错误",
    "Upload Failed.":"上传失败.",
    "Server (IO) Error":"服务器读写错误",
    "Security Error":"安全错误",
    "Upload limit exceeded.":"超出上传队列.",
    "Failed Validation.  Upload skipped.":"验证失败，跳过上传",
    "Upload interface failed to load, please ensure that the browser is already open support for JavaScript and Flash plug-in version is already installed can work.":
        "上传界面载入失败，请确保浏览器已经开启对JavaScript的支持，并且已经安装可以工作的Flash插件版本。",
    "Go to the Adobe website Get the latest Flash plug-in.":"请前往Adobe网站获取最新的Flash插件。",
    "Adobe website":"Adobe 网站",
    "End":"结束"
})