// Generated by CoffeeScript 1.3.3
(function() {
  var floatMenu;

  define(["jquery"], function($) {}, {
    constructor: function(a) {
      return this.host = 1;
    }
  }, floatMenu = function() {
    this.doms = {};
    this.doms.panel = $("<div style='position: fixed;'></div>");
    $("body").append(this.doms.panel);
    return this;
  }, floatMenu.prototype.addButton = function() {});

}).call(this);
