define({ "root":
//begin v1.x content
    ({
        "OK":"OK",
        "Upload":"Upload",
        "Cancel":"Cancel",
        "Cancel All":"Cancel All",
        "Select":"Select",
        "Select File":"Select File",
        "Select Files":"Select Files",
        "Close":"Close",
        "Type":"Type",
        "Name":"Name",
        "Size":"Size",
        "Status":"Status",
        "Waiting":"Waiting",
        "Waiting to complete":"Waiting to complete",
        "Upload complete":"Upload complete",
        "Upload Error":"Upload Error",
        "File name":"File name",
        "File size":"File size",
        "Message":"Message",
        "Error Code":"Error Code",
        "Error Message":"Error Message",
        "Please Select Files":"Please Select Files",
        "Select too many files":"Select too many files",
        "You have attempted to queue too many files.":"You have attempted to queue too many files.",
        "You have reached the upload limit.":"You have reached the upload limit.",
        "You may select one file.":"You may select one file.",
        "You may select up to $1 files.":"You may select up to $1 files.",

        "Select Fail":"Select Fail",
        "File size exceeds":"File size exceeds",
        "Size limit":"Size limit",
        "0-byte file":"0-byte file",
        "Invalid File Type":"Invalid File Type",
        "Allow file type":"Allow file type",
        "Unhandled Error":"Unhandled Error",
        "Cancelled":"Cancelled",
        "Stopped":"Stopped",


        "Upload Error":"Upload Error",
        "Upload Failed.":"Upload Failed.",
        "Server (IO) Error":"Server (IO) Error",
        "Security Error":"Security Error",
        "Upload limit exceeded.":"Upload limit exceeded.",
        "Failed Validation.  Upload skipped.":"Failed Validation.  Upload skipped.",
        "Upload interface failed to load, please ensure that the browser is already open support for JavaScript and Flash plug-in version is already installed can work.":"Upload interface failed to load, please ensure that the browser is already open support for JavaScript and Flash plug-in version is already installed can work.",
        "Go to the Adobe website Get the latest Flash plug-in.":"Go to the Adobe website Get the latest Flash plug-in.",
        "Adobe website":"Adobe website",
        "End":"End"
    })
    //end v1.x content
    ,
    "zh": true,
    "zh-tw": false,
    "tr": false,
    "th": false,
    "sv": false,
    "sl": false,
    "sk": false,
    "ru": false,
    "ro": false,
    "pt": false,
    "pt-pt": false,
    "pl": false,
    "nl": false,
    "nb": false,
    "ko": false,
    "kk": false,
    "ja": false,
    "it": false,
    "hu": false,
    "he": false,
    "fr": false,
    "fi": false,
    "es": false,
    "el": false,
    "de": false,
    "da": false,
    "cs": false,
    "ca": false,
    "ar": false
});
