define({ "root":
//begin v1.x content
    ({
        // 此处定义了所有form组件缺省语言包
        //全局设置
         "Delete":"Delete",
        "Remark":"Remark",
        "Submit":"Submit",
        "Cancel":"Cancel",
        "OK":"OK",
        "Tips":"Tips",
        "Close":"Close",
        "Open":"Open",
        "Add":"Add",
        "Edit":"Edit",
        "Select":"Select",
        "Preview":"Preview",
        //表单
        "Administrator Tools":"Administrator Tools",
        "Flow Log":"Flow Log",


        //表单操作部分
        "delete":"Delete",
        "submit":"Submit",
        "save":"Save",
        "expand":"Expand",
        "expandall":"Expand All",
        "collapse":"Collapse",
        "collapseall":"Collapse All",
        "invalide":"Invalide",
        "invalidedesc":"Process canceled / voided / termination",
        "close":"Close",
        "closedesc":"Do not save and close",
        "Return Frist":"Return Frist",
        "Return to the  drafter":"Return to the  drafter",
        "Return Previous":"Return Previous",
        "Return to the previous approver":"Return to the previous approver",
        "Reminders  approver":"Reminders  approver",
        "Reminders":"Reminders",


        "Please wait":"Please wait...",
        "Continue":"Continue",
        "The operation failed":"The operation failed",
        "Are you sure":"Are you sure?",
        "Do you want to save the document":"Do you want to save the document?",
        "Do you want to submit the document":"Do you want to submit the document?",
        "Do you want to invalidate the document":"Do you want to invalidate the document?",
        "Do you want to save the file without checking the validity of the input":"Do you want to save the file without checking the validity of the input?",
        "Are you sure close the document without saving":"Are you sure close the document without saving?",

        "Do you want to deal with permissions to be forwarded to another approver":"Do you want to deal with permissions to be forwarded to another approver?",
        "Invalid parameter, confirm parameters must have a return value, please contact your administrator":"Invalid parameter, confirm parameters must have a return value, please contact your administrator",
        "The current document have been  edit and save by others, please re-open the editor and submit or save":"The current document have been  edit and save by others, please re-open the editor and submit or save",
        //以下文字在ls内
        "Universalid":"Universalid",
        "Agent Error":"Agent Error",
        "Save Success":"Save Success",
        "Next step":"Next step",
        "Status":"Status",
        "Approver":"Approver",

        "Operation was successful":"Operation was successful",
        "Submitted successfully, waiting for the system has finished processing":"Submitted successfully, waiting for the system has finished processing",
        "The document has been forwarded to":"The document has been forwarded to",
        "The process has been terminated":"The process has been terminated",
        "Create a new process documentation":"Create a new process documentation",
        "Unknown error":"Unknown error",
        "An unknown error into debug mode, collect error and sent to noteshelp.":"An unknown error into debug mode, collect error and sent to noteshelp.",
        //转发
        "Transfer":"Transfer",
        "Transfer To":"Transfer To",
        "Transfer to other":"Transfer to other",
        "Please select transfer to":"Please select transfer to",
        cancel:"Cancel",
        ok:"OK",
        confirm:"Confirm",
        //提醒消息
        "Can not find the application database":"Can not find the application database",
        "Please contact the administrator.":"Please contact the administrator.",
        "Have taken place in the e-mail to remind $user":"Have taken place in the e-mail to remind $user",
        "You have sent reminders, do not re-send":"You have sent reminders, do not re-send",
        //状态操作
        "Can handle state":"Can handle state:",
        "The current deal with":"Current dealer:",
        "The current state of":"Current state :",
        "Creator":"Creator:",
        "Creation time":"Creation time:",
        "Document Number":"No.:",

        //区段
        "Signature":"Signature:",
        //附件组件语言包
        attachment:"Attachment",
        attachmentselect:"Select File",
        upload:"Upload",
        uploadtitle:"Upload File",
        uploaderrortitle:"Upload Error",
        uploadinstructions:"Maximum file size limit 10MB.If the file is larger than 10MB will result in a captured exception.",
        uploaderror:"File upload error occurs, this is usually due to error because of your file exceeds 10MB.",
        filetypeerror:"The file type is not allowed to upload, please re-select the file.",
        pleaseselectfile:"Please select file.",
        uploading:"Uploading ,please waiting.",
        deleting:"Deleting ,please waiting.",
        delerrortitle:"Delete Error",
        delereordescript:"Throw a delete error.Please contact the administrator that if you are the author of a document.",
        "The file name can not contain the following characters:":"The file name can not contain the following characters:",
        "Invalid file or zero-byte file, please re-upload.":"Invalid file or zero-byte file, please re-upload.",
        "Invalid file":"Invalid file",
        "Tables failed to initialize, Please Refresh try.If the problem persists, please contact management.":"Tables failed to initialize, Please Refresh try.<br>If the problem persists, please contact management.",
        "Please save the document and then download or preview.":"Please save the document and then download or preview.",
        "End":"End"
    })
    //end v1.x content
    ,
    "zh": true,
    "zh-tw": false,
    "tr": false,
    "th": false,
    "sv": false,
    "sl": false,
    "sk": false,
    "ru": false,
    "ro": false,
    "pt": false,
    "pt-pt": false,
    "pl": false,
    "nl": false,
    "nb": false,
    "ko": false,
    "kk": false,
    "ja": false,
    "it": false,
    "hu": false,
    "he": false,
    "fr": false,
    "fi": false,
    "es": false,
    "el": false,
    "de": false,
    "da": false,
    "cs": false,
    "ca": false,
    "ar": false
});
