define({ "root":
//begin v1.x content
    ({
        // 此处定义了所有form组件缺省语言包
        //全局设置
        "LABEL":"NAME",
        "Home":"Home",
        "Login":"Login",
        "Logout":"Logout",
        "Refresh":"Refresh",
        "Todo":"Todo",
        "Notes":"Notes",
        "Password":"Password",
        "Change Password":"Change Password",
        "Mail":"Mail",
        "User Name":"User Name",
        "Name":"Name",
        "User":"User",
        "BBS":"BBS",
        "Settings":"Settings",
        "Person Settings":"Person Settings",
        "Internal Forum":"Internal Forum",
        "IT Support":"IT Support",
        "Welcome":"Welcome",
        "Today":"Today",
        "Today is":"Today is",
        "Week":"Week",
        "Service Hotline":"Service Hotline",
        "XXX Digital Technology Co., Ltd. All Rights Reserved":"XXX Digital Technology Co., Ltd. All Rights Reserved",
        "Select department":"Select department",
        "Root":"Root",
        "Delete":"Delete",
        "Remark":"Remark",
        "Submit":"Submit",
        "Cancel":"Cancel",

        "OK":"OK",
        "Tips":"Tips",
        "Close":"Close",
        "Open":"Open",
        "Add":"Add",
        "Edit":"Edit",
        "Copy":"Copy",
        "Copy success.":"Copy success.",
        "The browser does not support auto-copy, manually copy the following text.":
            "The browser does not support auto-copy, manually copy the following text.",
        "Select":"Select",
        "Empty":"Empty",
        "Clear":"Clear",
        "Search":"Search",
        "Please Select":"Please Select",
        "Invert Selection":"Invert Selection",
        "Select All":"Select All",
        "Click the path selection":"Click the path selection",
        "Module failed to load":"Module failed to load",
        "This problem may be due to network or program error":"This problem may be due to network or program error",
        "Later to refresh such as invalid, please contact the administrator or developer":"Later to refresh such as invalid, please contact the administrator or developer",
        "Equal":"Equal",
        "Greater":"Greater",
        "Less":"Less",


        "End":"End"

    })
    //end v1.x content
    ,
    "zh": true,
    "zh-tw": false,
    "tr": false,
    "th": false,
    "sv": false,
    "sl": false,
    "sk": false,
    "ru": false,
    "ro": false,
    "pt": false,
    "pt-pt": false,
    "pl": false,
    "nl": false,
    "nb": false,
    "ko": false,
    "kk": false,
    "ja": false,
    "it": false,
    "hu": false,
    "he": false,
    "fr": false,
    "fi": false,
    "es": false,
    "el": false,
    "de": false,
    "da": false,
    "cs": false,
    "ca": false,
    "ar": false
});
